### ISSUE TITLE
Could not instantiate `JsonRpcProvider`

### ISSUE THREAD

**Issue by mislam** [pokt-network/pocket-js#35]
```javascript
import { JsonRpcProvider } from '@pokt-foundation/pocketjs-provider'

const rpcUrl = 'https://node1.testnet.pokt.network:443'

const dispatchers = [
  'https://node1.testnet.pokt.network',
  'https://node2.testnet.pokt.network',
  'https://node3.testnet.pokt.network',
  'https://node4.testnet.pokt.network',
  'https://node5.testnet.pokt.network',
]

const provider = new JsonRpcProvider({
  rpcUrl,
  dispatchers,
})
```

throws this error:
```
dispatcher.js:5 Uncaught TypeError: Class extends value #<Object> is not a constructor or null
    at node_modules/undici/lib/dispatcher.js (dispatcher.js:5:1)
    at __require (chunk-IGMYUX52.js?v=e726772f:40:50)
    at node_modules/undici/lib/dispatcher-base.js (dispatcher-base.js:3:20)
    at __require (chunk-IGMYUX52.js?v=e726772f:40:50)
    at node_modules/undici/lib/client.js (client.js:9:24)
    at __require (chunk-IGMYUX52.js?v=e726772f:40:50)
    at node_modules/undici/index.js (index.js:3:16)
    at __require (chunk-IGMYUX52.js?v=e726772f:40:50)
    at index.js:120:29
```

**Platform to reproduce:**
Browser: Brave v1.37.111 Chromium: 100.0.4896.79 (Official Build)
OS: macOS Monterey v12.3.1

**Comment by Evalir** [comment]
Hey! On which platform are you trying to instantiate the provider? Is it on a browser or on Node?

**Comment by mislam** [comment]
On a browser (Brave).

**Comment by Evalir** [comment]
This is due to `JsonRpcProvider` being node only—you'll be able to use `IsomorphicProvider` for web work.

Closing this issue as this is not actually a problem. We'll include more docs to make sure people choose the correct provider.
